services:
  proxy:
    image: nginxproxy/nginx-proxy
    restart: always
    container_name: "proxy"
    environment:
      - DEFAULT_HOST=node-red.local
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - "certs:/etc/nginx/certs"
      - "vhost:/etc/nginx/vhost.d"
      - "html:/usr/share/nginx/html"

  letsencrypt:
    image: nginxproxy/acme-companion
    volumes:
      - "certs:/etc/nginx/certs"
      - "vhost:/etc/nginx/vhost.d"
      - "html:/usr/share/nginx/html"
      - "/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/ssl/certs/:/etc/ssl/certs/:ro"
    environment:
      -  NGINX_PROXY_CONTAINER=proxy
      -  ACME_CA_URI=https://step.home:9000/acme/acme/directory
    networks:
      - step-ca_default
      - proxy
    restart: "always"
    depends_on: ["proxy"]


networks:
  proxy:
  step-ca_default:
    external: true

volumes:
  certs:
  vhost:
  html:


